### ISSUE TITLE
Review licensing

### ISSUE THREAD

**Issue by ExcaliburZero** [Infinite-Dango-Studios/ganbatte#1]
Review and decide on the licensing for the various parts of the project. The licensing will be split between the files added by Ren'Py, the code of the game, the art, and the writing/text.

The licensing of the project is currently not set in stone. My recommendations for the licenses to use are as follows:
- All of the content created by the Ren'Py program must be licensed as specified in the README.md file.
- **Code:** [The MIT License](http://opensource.org/licenses/MIT)
- **Art:** [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/)
- **Writing:** [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/)

The CC BY-NC-ND 3.0 license for the writing and art will allow the art and writing to be shared as long as credit is given and it will prevent their use for commercial purposes. This will allow for the game to be posted online without issue and prevent people from using the art and writing for commercial purposes. Please read up on the CC BY-NC-ND 3.0 license (through the link above) to get an understanding of exactly what it means.

If you have any concerns or suggestions about the licensing, feel free to let me know.

**Comment by Sabre-Hecate** [comment]
Hey, Sabre here. As to the licencing for writing and art, it says that it will prevent commercial use. Will it prevent OUR commercial use of it? Furthermore, if....someone....were to take the script and write a light novel adaptation for publishing, would it prevent that person from publishing it? That person being me.

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
The license will not prevent you from later reusing the content for other purposes.

The license means that you are allowing other people to use it as defined by the license, however you, as the author, may use the content in any way you wish, as the license only restricts how people other than the author can use it.

**Comment by juanitaylor** [comment]
ok. sounds good to me~

**Comment by ExcaliburZero** [comment]
Has everyone reviewed the licensing?

**Comment by ExcaliburZero** [comment]
If no one has any other questions then I will close this issue.

**Comment by ExcaliburZero** [comment]
Okay, since no one else has had any questions on this, I will close this issue.
