### ISSUE TITLE
Studio name

### ISSUE THREAD

**Issue by ExcaliburZero** [Infinite-Dango-Studios/ganbatte#10]
So we will need to come up with a name for our studio. Some brainstorming on this has been done in #9, but a final decision has not yet been reached.

Some of the ideas that have been presented are:
- X Dango Studios (where X is replaced by the number of staff members in the studio)
- Infinite Dango Studios 
- Dangoes At The Studio
- Hella Losers Club Studios
- Ganbatte Studios
- Dango Away Studios

We need to either choose from one of the above names, or come up with a new name for the studio.

**Comment by juanitaylor** [comment]
Don't like us? Dango Away studios
I spent extra time coming up with that one

**Comment by ExcaliburZero** [comment]
"Dango Away Studios" sounds like it could be good.

**Comment by juanitaylor** [comment]
like, then go away?
I'm as trashy as my icon omg

**Comment by juanitaylor** [comment]
wait seriously??? oh lord

**Comment by ExcaliburZero** [comment]
It looks like there shouldn't be any search engine problems with "Dango Away Studios". Really the only time "dango" and "away" are used in the same sentence is when someone is talking about Clannad and Spirited Away.

**Comment by juanitaylor** [comment]
weird mix? but that is a good thing

**Comment by Sabre-Hecate** [comment]
:dango:

**Comment by juanitaylor** [comment]
:dango::dango::dango::dango::dango::dango::dango::dango::dango::dango::dango::dango::dango:

**Comment by juanitaylor** [comment]
dango away
I'm so proud

**Comment by ExcaliburZero** [comment]
At this point I'd recommend either "Infinite Dango Studios" or "Dango Away Studios".

**Comment by juanitaylor** [comment]
I wonder if there's a way to make a poll on Github?????

**Comment by ExcaliburZero** [comment]
@juanitaylor 
I don't think there is, but also it would be better to handle the voting ourselves. Since there aren't many people who would vote, and since the First Past the Post voting system is rubbish.

**Comment by ExcaliburZero** [comment]
If it does come down to a vote for the studio name I recommend we use the Approval Voting system, as it is quick and accurate. See this video for a quick explanation: http://youtu.be/orybDrUj4vA

**Comment by Sabre-Hecate** [comment]
I'm a fan of Infinite Dango. It carries the message of X Dango, but it allows for a fluid number so if we ever do another project and we add more team members, it stands. We are a growing studio. IDK...

**Comment by juanitaylor** [comment]
At the same time, Infinite Dango changes, and it would be awkward to have it change for each new project. We could actually use the name "Infinite," it has a kind of cool ring

**Comment by Sabre-Hecate** [comment]
Huh? I thought the point of Infinite Dango was that it didn't change...

Infinite Studios already exists.

**Comment by Sabre-Hecate** [comment]
Hey, I just realized, I'm like the founder of this studio, right? Because I watched Saekano and decided that I wanted to make a dating sim, and I gathered everyone~!

**Comment by juanitaylor** [comment]
sigh

**Comment by ExcaliburZero** [comment]
Does anyone else have any other ideas for the name of the studio, or should we try to come to a decision?

**Comment by ExcaliburZero** [comment]
Should we try to come to a decision on the name now?

**Comment by Sabre-Hecate** [comment]
Sure~!

**Comment by juanitaylor** [comment]
http://goo.gl/AzDhbY
I know we said no poll but polls are so easy and make sense so I made one
vote
or don't

**Comment by ExcaliburZero** [comment]
I think for choosing the name we should just list the names in the order we want them. Polls are quite bad systems that aren't really good for making decisions accurately. I think we'd be best off using the [Alternative Vote system](https://www.youtube.com/watch?v=3Y3jE3B8HsE), which tends to be a lot more accurate for a number of reasons.

Essentially how it works is that each person ranks in order the names that they want, and then there is a way to determine from the results what the most agreeable choice is. It shouldn't be too complicated of a system, and it should prevent any issues of voting splits on similar names (e.x. choosing between "Infinite Dango Studios" and "Dango Away Studios").

---

If we go with that system, then this will be my vote:
1. Infinite Dango Studios
2. Dango Away Studios
3. Ganbatte Studios
4. Dangoes At the Studio
5. Hella Losers Club Studios

**Comment by Sabre-Hecate** [comment]
In that case, my numerical would be:
1. Infinite Dango
2. Dango Away Studios
3. Ganbatte Studios

4/5 Dangoes @ the Studio and HLCS.  (I think they're equally so-so)

**Comment by juanitaylor** [comment]
alright I guess that works too
1. Dango Away Studios
2. Infinite Dango Studios
3. X Dango Studios (with a numeral)
4. Hella Losers Club Studios
5. Ganbatte Studios
6. Dangoes at the Studios

**Comment by boxesofflowers** [comment]
1. Hella Losers Club
2. Ganbatte Studios
   those are pretty much my preferences, :)

**Comment by ghost** [comment]
1.) Hella Losers Club
2.) Dango Away Studios
3.) Ganbatte Studios
I like them all, but these have nice rings to them, in my opinion. ;v;

**Comment by ExcaliburZero** [comment]
Okay, I have gone through the votes and here are the results, feel free to skip to the end for the end result if you are not interested in the voting logics:

---

Initial round:
- Dango Away Studios - 1
- Infinite Dango Studios - 2
- Hella Losers Club - 2
- Ganbatte Studios - 0
- Dangoes at the Studios - 0

Ganbatte Studios and Dangoes at the Studios received no points, so they were eliminated. Dango Away Studios had the least number of points out of the choices that were left, so it was eliminated.

The vote for Dango Away Studios was redistributed to its voter's second choice, Infinite Dango Studios.

Round 2:
- Infinite Dango Studios - 3
- Hella Losers Club - 2

---

The winning choice is thus **Infinite Dango Studios**.

**Comment by Sabre-Hecate** [comment]
:dango:  Infinite Dango~! :dango:

**Comment by Sabre-Hecate** [comment]
So now, as soon as we get an avatar logo and a cover photo logo thing I can make a promotional FB page!

**Comment by ExcaliburZero** [comment]
Tomorrow I'll try working on setting up a GitHub organization for the group and transfer over the repository to the organization.

**Comment by Sabre-Hecate** [comment]
Sounds good~ :dango:

**Comment by ExcaliburZero** [comment]
I'll close this issue since we have decided upon a name, but feel free to continue commenting on it.
