### ISSUE TITLE
Jacoba Wanted to Know Something

### ISSUE THREAD

**Issue by ghost** [Infinite-Dango-Studios/ganbatte#11]
Hi, guys! So Jacoba wanted me to ask about the flowers and hearts. Do we want buds on them, or no?

**Comment by ExcaliburZero** [comment]
Do you mean the characters hearts as in #7? If so then you may want to post on that issue.

**Comment by ghost** [comment]
Oh-- Okay. I'm sorry about that. I'll do that, then.

**Comment by ExcaliburZero** [comment]
Okay, I'll close this issue then.
