### ISSUE TITLE
Need game logo

### ISSUE THREAD

**Issue by ExcaliburZero** [Infinite-Dango-Studios/ganbatte#15]
We currently are in need of a logo for the game. Currently I have added in a [dummy / preliminary logo](https://github.com/ExcaliburZero/ganbatte/blob/1a28878399f348b2ba3493a4b1d3756c5571d972/game/images/misc/logo.png) into the game, which can be easily changed out with a new logo. We also will need the logo for advertising purposes.

The logo will need to include the name of the game (Ganbatte), and it should fit in with the color scheme of the game. We may also want to include a design into it to reference the theming of the game.

So we will need to decide upon what the logo will be like, and then we will need to have someone make the logo into an image file. The image file will need to have a large resolution and a transparent background.

**Comment by boxesofflowers** [comment]
I will get on this, I know exactly what to do.

**Comment by boxesofflowers** [comment]
![logo](https://cloud.githubusercontent.com/assets/11141654/6656612/3b7f96fc-cb05-11e4-8f8b-dfbb64df04af.png)

yes? no?

**Comment by ExcaliburZero** [comment]
It looks good, but the game's name seems a bit difficult to read. Also it might be better to spread out the elements of it a bit to have more of a rectangular shape.

**Comment by boxesofflowers** [comment]
![logo alternate](https://cloud.githubusercontent.com/assets/11141654/6656861/41060a30-cb0e-11e4-8b4d-ceceed734a5c.png)
I made the name horizontal and tried to spread things out. if you wanted even more "marquee" style I'd change the design.

**Comment by ExcaliburZero** [comment]
That looks good. The text is a bit easier to read. It stills seems a little bit difficult to read, but that might just be me.

Do you want to try adding it into the game?

**Comment by Sabre-Hecate** [comment]
THEY'RE PRETTY~! NOW IF WE JUST HAVE AN AVATAR SIZED PIC SIMILAR I CAN MAKE AN FB PAGE FOR GANBATTE. Then once we decide studio and get an Avatar/cover for that I can make a FB page for that too.

**Comment by juanitaylor** [comment]
gorgeous work~~

**Comment by ExcaliburZero** [comment]
I have added the game logo and icon that boxesofflowers made into the game with a82f59830a44be5b387bfa8aa611847ef30338c8 and 3e5cf47c0418312a4d9467c89a2425d2bd9ed414 .

**Comment by ExcaliburZero** [comment]
Since we now have the logo made up, and the working on the logos, etc. has moved to #16 , I will close this issue.
