### ISSUE TITLE
Facebook Icons and Cover Photos

### ISSUE THREAD

**Issue by Sabre-Hecate** [Infinite-Dango-Studios/ganbatte#16]
Hey, so now that we've decided the name of the Studio to be "Infinite Dango Studios" we can move forward with preparations for marketing. Even now this early in development we can get some news out. For this reason I intend to create a "Brand/Product" page for Ganbatte and an "Entertainment page" for Infinite Dango Studios. To do this, however, I will need roughly four pictures for each. An avatar, one advertising Ganbatte and one advertising IDS (perhaps a studio symbol?). I'll also need a long cover photo for each. The current Ganbatte logo might work for the Ganbatte cover photo, but we'll still need one for IDS. Sometime in the future, I'd also like cute chibi art of Chris, Jacoba, Priscilla, Annissa and Me (preferably holding a dango stick and something which represents our studio job) in order to make "Meet the members" posts. Those chibi arts aren't super priority, though. The priority of this issue is the two avatars and two cover photos. @boxesofflowers  you've done the logos so far, but if @ChocoTacoKitty or @juanitaylor wants to handle it, it's up to you guys.

Arigatou gozaimasu~!!!! :dango:

**Comment by Sabre-Hecate** [comment]
Update: The logo will definitely work as a cover for the Ganbatte page. I just checked it. Parts of it are cut off, but it still works.

**Comment by boxesofflowers** [comment]
I'll do some sketches today, if you like them I'll convert them to finished products :)

**Comment by boxesofflowers** [comment]
![facebook icon ganbtte](https://cloud.githubusercontent.com/assets/11141654/6696272/7544dd42-ccbe-11e4-8f70-3fdab9e1df12.png)
here's what i was thinking for the ganbatte page's icon...

and here are the sketches for infinite dango studios:
![studio logo 1](https://cloud.githubusercontent.com/assets/11141654/6696306/c10eafdc-ccbe-11e4-8ef4-16cb97e509ba.png)
![studio logo 2](https://cloud.githubusercontent.com/assets/11141654/6696309/c6fb5d78-ccbe-11e4-8ccb-0b4e8be698af.png)

ba bang!

**Comment by Sabre-Hecate** [comment]
YES! I LIKE ALL OF IT! Merci~!

**Comment by ExcaliburZero** [comment]
@boxesofflowers 
Those look quite good.

**Comment by boxesofflowers** [comment]
Here's the studio logo:
![infinite dango 1](https://cloud.githubusercontent.com/assets/11141654/6745125/080b3452-ce89-11e4-90c3-c6b8f9be24f6.png)
I'll add the icon tomorrow, it's not done quite yet! :)

**Comment by Sabre-Hecate** [comment]
It's so candy colored and pastel, I LOVE IT!!! :dango:

**Comment by ExcaliburZero** [comment]
@boxesofflowers 
The studio logo looks really good.

**Comment by boxesofflowers** [comment]
@Sabre-Hecate @ExcaliburZero thanks guys! here's the icon:
![studio icon](https://cloud.githubusercontent.com/assets/11141654/6761921/99068592-cf2e-11e4-8ccb-0edbf0bb83bb.png)
:)

**Comment by ExcaliburZero** [comment]
@boxesofflowers 
Those look good. Can you send me a copy of them with transparent backgrounds or add them to the site repo so I can work them into the site's design?

**Comment by Sabre-Hecate** [comment]
Commenting on a closed issue just to say like, wow and thanks! There are amazing!

**Comment by ExcaliburZero** [comment]
Since boxesofflowers has made and sent in the logos and icons, I will close this issue.
