### ISSUE TITLE
couple of things on my end

### ISSUE THREAD

**Issue by juanitaylor** [Infinite-Dango-Studios/ganbatte#9]
oooookay so firstly I figured out that the artists have a buttload of art to do
we have:
-450+ character sprites
-75+ backgrounds
-100+ CGs

These things take a lot of time, and in the name of efficiency we'd like to request more help from more artists. @ChocoTacoKitty and I know someone who could maybe help, their name is Adrian. I was also thinking that Priscilla could help, right @Sabre-Hecate ? We especially think the backgrounds will be tough, so someone to just do filler work (detail stuff in the bgs) would be really nice.

@ChocoTacoKitty and I compared this to another dating game we've both played, called DRAMAtical Murder by Nitro+Chiral. It's very similar to this game in format, so we're using it as a sort of basis. I bring this up because I'd like to point out that a whole team of artists worked on the art for that game- not just two. 

Second, I'm not really prepared to do much digital art. I don't have a way to get scans onto my 3DS, so for right now I'm just working on sketches and concepts. I'm hoping we can do BGs on paper and scan them to put right into the game, with little to no digital editing. As far as sprites go though, my hands are tied. A computer based program is difficult because my parents are kinda anuses about me being on the computer a lot. I was thinking I could send scans to another artist who could tidy them up?

Thirdly, I don't know how much @ExcaliburZero knows about this, but @Sabre-Hecate  and I have been thinking of having my sister work on the background music. She can do guitar, piano, and singing, and we're working on composing things together. Just wanted to throw that out there.

Cheers guys! Let's keep at it!

**Comment by Sabre-Hecate** [comment]
Holy art, Batman~!

I'm fine with adding those two, as long as they understand our vision and stuff~! I definitely understand what you're saying about huge ass amounts of art.

**Comment by ExcaliburZero** [comment]
If you can get other people to help out then that would be great. We could use as many people as we can get. Anyone who wants to help out should make a GitHub account so they can use the Issue Tracker.

While I can't do a lot digital art, I am familiar with the processes behind it, and I can help with getting people up to speed on how to do it.

Anything that needs to be done computer-side I can help with.

**Comment by juanitaylor** [comment]
omg do we understand our vision?

right, I'll do my best to get them in the loop. And thank you again- feel free to pick up helpers when you need them too; the more the merrier!!

**Comment by Sabre-Hecate** [comment]
It felt like the standard phrase for when more people join a group :P 

WHAT'S OUR STUDIO GOING TO BE CALLED!?!?

**Comment by juanitaylor** [comment]
ganbatte, obviously

**Comment by Sabre-Hecate** [comment]
Ganbatte studios making the game Ganbatte? Seems legit. :dango:

**Comment by juanitaylor** [comment]
aw yeah
total legitimacy

**Comment by ExcaliburZero** [comment]
The team that made Katawa Shoujo was named Four Leaf Studios.

I'd recommend against using just Ganbatte for the studio name, for search engine optimization reasons. I'm not sure whether Ganbatte Studios would work well or not. I'll do some quick research.

**Comment by Sabre-Hecate** [comment]
:dango:  :dango:  :dango:

**Comment by Sabre-Hecate** [comment]
:dango: Three Dango Studios :dango:

**Comment by Sabre-Hecate** [comment]
Kidding

**Comment by ExcaliburZero** [comment]
From my quick research, there was one former company in Florida in 2012 called "Ganbatte Studios LLC", and one artist on Facebook who goes by the username "Ganbatte Studios"

**Comment by Sabre-Hecate** [comment]
We have to kill him.

**Comment by Sabre-Hecate** [comment]
There can only be one

**Comment by Sabre-Hecate** [comment]
Battle Royale rules.

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
You mean "her" right?

Also there is a company called "CrossFit Ganbatte" that has gym studios.

**Comment by ExcaliburZero** [comment]
In total it looks like there shouldn't be too many search engine issues with "Ganbatte Studios".

**Comment by Sabre-Hecate** [comment]
Yes. Her.. And we shall destroy that gym.

**Comment by juanitaylor** [comment]
3 dango studios works
though we should say like 6 dango studios
because there will be 6 people and they're all dangoes

**Comment by ExcaliburZero** [comment]
The only thing that concerns me about the name "Ganbatte Studios" is the facebook page. It should be fine, but if we can come up with something different that isn't being used at all, then that might be better.

"Three Dango Studios" / "3 Dango Studios" could work.

**Comment by Sabre-Hecate** [comment]
_cries because I made that up as a joke_

YESSSSSSSSS, WE ARE A DAIKAZOKU OF DANGO. A DANGO DAIKAZOKU IF YOU WILL. 

:dango: :dango: :dango: 6 Dango Studios :dango: :dango: :dango:

**Comment by ExcaliburZero** [comment]
If you want to do the number being based on the number of staff, we could do "Infinite Dango Studios". Because we don't know for sure how many people might join the studio.

**Comment by Sabre-Hecate** [comment]
Infinite Dango? _swims in swimming pool of dango_   _Constructs a statue of Nagisa and Ushio out of dango_  DANGO, DANGO, DANGO, DAIKAZOKU

**Comment by juanitaylor** [comment]
certainly
or we could do Dangoes At The
so it would be Dangoes At The Studios

**Comment by juanitaylor** [comment]
I just said 6 because it's 6 so far
the name can be "infinite" until the game comes out then we'll tally our forces

**Comment by Sabre-Hecate** [comment]
Yes, tally the forces when we finish!

**Comment by ExcaliburZero** [comment]
"Dangoes At The Studios" looks kind of odd. I don't feel like it flows very well.

We may not want to have a set number if we go with "X Dango Studios", because if for any reason it varies, then it could be a bit awkward of a situation.

**Comment by juanitaylor** [comment]
this is true
perhaps we could be "Hella Losers Club Studios"
oooh do we need a logo?

**Comment by ExcaliburZero** [comment]
We will need a logo. Though it might be best to make it as a vector graphic (.svg) so resizing it will never be a problem. As vector graphics can be resized to any size without issue.

**Comment by juanitaylor** [comment]
hm. I'll have to get on that later now I have sprite work _cries_

**Comment by Sabre-Hecate** [comment]
You can do it :v:

**Comment by ExcaliburZero** [comment]
Ganbatte!

**Comment by juanitaylor** [comment]
aaaaaaaaaaaaaaah good one
I see what you did there

**Comment by juanitaylor** [comment]
![](http://emojipedia.org/wp-content/uploads/2014/04/1f361-google-android.png.pagespeed.ce.Orjn1BoJy6.png)

**Comment by ExcaliburZero** [comment]
I think I will open a new issue for coming up with the studio name.

**Comment by juanitaylor** [comment]
good thinking!

**Comment by Sabre-Hecate** [comment]
DANGO~!

**Comment by ExcaliburZero** [comment]
I have setup an issue on the name of the studio at #10.

**Comment by ExcaliburZero** [comment]
Since no one else has made any comments on this issue for about a month, I will close this issue.
